config/routes.rb
AgencyBox::Application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :expenses
  
  namespace :expense do
    resources :categories, :only => [:new]
    get "categories/:slug" => "categories#show", as: "category"
    resources :categories, :except => [:show, :new]
  end

  namespace :leave do
    resources :categories
  end

  resources :leaves

  resources :users, only: [:index, :show]
  get "profile/edit" => "users#edit", as: "edit_user"
  patch "users/:id" => "users#update", as: "update_user"

  get "message/:id/new" => "message#new", as: :message_new
  post "message/:id/create" => "message#create", as: :message_create
  get "message/inbox" => "message#inbox", as: "message_inbox"
  get "message/sent" => "message#sent", as: "message_sent"

  get "message/:id/reply" => "message#new_reply", as: :message_reply_new
  post "message/:id/reply" => "message#send_reply", as: :message_send_reply
  get "message/:id/" => "message#show", as: :message_show

  resources :projects, :except => [:show, :edit]
  get "projects/:slug" => "projects#show", as: "project_show"
  get "projects/:slug/edit" => "projects#edit", as: "edit_project"
  patch "projects/:slug/update" => "projects#update"

  get "projects/:slug/members/add" => "project_members#new", as: "add_project_members"
  post "projects/:slug/members/add" => "project_members#create"
  
  get "tickets/" => "tickets#index"
  namespace :project do 
    get ":namespace_slug/tickets/new" => "tickets#new", as: :new_ticket
    get ":namespace_slug/tickets/" => "tickets#index", as: :tickets
    get ":namespace_slug/tickets/:id" => "tickets#show", as: :ticket
    get ":namespace_slug/tickets/:id/edit" => "tickets#edit", as: :edit_ticket
    post ":namespace_id/tickets" => "tickets#create"
    patch ":namespace_slug/tickets/:id/edit" => "tickets#update"
  end

  post "ticket/:ticket_id/ticket_comment/create" => "ticket_comment#create", as: :ticketcomment_create

  resources :leads do
      collection do
          delete :delete_multiple
      end
  end
  get "leads/dashboard"
  post "leads/convert", as: :convert_lead
 
  namespace :lead do
      resources :sources do
          collection do
              delete :delete_multiple
          end
      end
  end

  

end

app/controllers/expense/categories_controller.rb
class Expense::CategoriesController < ApplicationController
    before_filter :authenticate_user!

    def index
        @all = ExpenseCategory.all
    end

    def new
        @category = ExpenseCategory.new
    end

    def create
        @category = ExpenseCategory.new create_category_params
        if @category.valid?
            @category.save
            redirect_to :expense_categories
        else
            render :new
        end
    end

    def edit
        @category = ExpenseCategory.find params[:id]
    end

    def update 
        @category = ExpenseCategory.find params[:id]
        @category.assign_attributes create_category_params
        
        if @category.valid?
            @category.save
            redirect_to expense_category_path(slug: @category.slug)
        else
            render :edit
        end
    end

    def show
        @category = ExpenseCategory.find_by slug: params[:slug]
    end

    private

    def create_category_params
        params.require(:expense_category).permit(:name, :description)
    end

end

app/controllers/leave/categories_controller.rb
class Leave::CategoriesController < ApplicationController
    before_filter :authenticate_user!


    def new
        @category = LeaveCategory.new
    end

    def create
        @category = LeaveCategory.new new_category_params
        if @category.valid?
            @category.save
            redirect_to :leave_categories
        else
            render :new
        end
    end
    
    def index
        @categories = LeaveCategory.all
    end

    def show
        @category = LeaveCategory.find params[:id]
    end

    def edit
        @category = LeaveCategory.find params[:id]
    end

    def update 
        @category = LeaveCategory.find params[:id]
        @category.assign_attributes new_category_params
        
        if @category.valid?
            @category.save
            redirect_to leave_category_path(@category)
        else
            render :edit
        end
    end


    private

    def new_category_params
        params.require(:leave_category).permit(:name, :description)
    end
end

app/controllers/leave_controller.rb
class LeaveController < ApplicationController
    before_filter :authenticate_user!

    def new
        @leave = LeaveApplication.new
    end

    def create
        @leave = LeaveApplication.new new_leave_params
        if @leave.valid?
            @leave.user = current_user
            @leave.save
            redirect_to :leave_index
        else
            render :new
        end
    end

    def index
        if current_user.has_role? :admin
            @leaves = LeaveApplication.all
        else
            @leaves = LeaveApplication.where user: current_user
        end
        if params.include?("status")
            if params['status'] == "pending"
                @leaves = @leaves.where({ :status => false, :rejected => false })
            elsif params["status"] == "approved"
                @leaves = @leaves.where({ :status => true, :rejected => false })
            elsif params["status"] == "rejected"
                @leaves = @leaves.where({ :status => false, :rejected => true })
            end
        end

        if params.include?(:amount_filter)
            if params[:amount_filter] == "asc"
                @leaves = @leaves.order("start_date ASC")
            elsif params[:amount_filter] == "desc"
                @leaves = @leaves.order("start_date desc")
            end
        end

        if params.include?(:user)
            if current_user.has_role? :admin
                @leaves = @leaves.where(:user_id => params[:user])
            end
        end

        @users = User.all
    end

    def show
        @leave = LeaveApplication.find params[:id]
    end


    private

    def new_leave_params
        params.require(:leave_application).permit(:start_date, :end_date, :reason, :category_id)
    end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
    before_filter :authenticate_user!

    def new
        @leave = LeaveApplication.new
    end

    def create
        @leave = LeaveApplication.new new_leave_params
        if @leave.valid?
            @leave.user = current_user
            @leave.save
            flash[:notice] = "Leave successfully created"
            UserMailer.new_leave(@leave).deliver
            redirect_to leaves_path
        else
            render :new
        end
    end

    def edit
        @leave = LeaveApplication.find params[:id]
    end

    def update
        leave = LeaveApplication.find params[:id]
        leave_status = params[:leave_status]
        if leave_status == "Approved"
            leave.status = true
            leave.rejected = false
        elsif leave_status == "Pending"
            leave.status = false
            leave.rejected = false
        elsif leave_status == "Rejected"
            leave.status = false
            leave.rejected = true
        end
        leave.save
        redirect_to leave_path(leave)
    end

    def index
        if current_user.has_role? :admin
            @leaves = LeaveApplication.all
        else
            @leaves = LeaveApplication.where user: current_user
        end
        if params.include?("status")
            if params['status'] == "pending"
                @leaves = @leaves.where({ :status => false, :rejected => false })
            elsif params["status"] == "approved"
                @leaves = @leaves.where({ :status => true, :rejected => false })
            elsif params["status"] == "rejected"
                @leaves = @leaves.where({ :status => false, :rejected => true })
            end
        end

        if params.include?(:amount_filter)
            if params[:amount_filter] == "asc"
                @leaves = @leaves.order("start_date ASC")
            elsif params[:amount_filter] == "desc"
                @leaves = @leaves.order("start_date desc")
            end
        end

        if params.include?(:user)
            if current_user.has_role? :admin
                @leaves = @leaves.where(:user_id => params[:user])
            end
        end

        @users = User.all
    end

    def show
        @leave = LeaveApplication.find params[:id]
    end


    private

    def new_leave_params
        params.require(:leave_application).permit(:start_date, :end_date, :reason, :category_id)
    end
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leave/categories/edit.html.erb
<button class='btn btn-info btn-lg bottom-flat'>Edit Leave Category</button>
<div class='well'>
<% if @category.errors.any? %>
    <p class='alert alert-danger'>Errors</p>
    <% @category.errors.full_messages.each do |e| %>
        <p class='text-danger'><%= e %></p>
    <% end %>
<% end %>
<%= form_for @category, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    <br />
    <%= f.text_area :description, size: "60x12", class: 'form-control', placeholder: 'Description'   %>
    <br />
    <%= f.submit "Edit", class: "btn btn-primary"%>

<% end %>
</div>

app/views/leave/categories/index.html.erb
<button class='btn btn-info btn-lg bottom-flat'>Leave Categories</button>
<div class='well'>
<% @categories.each do |category| %>
    <button class='btn btn-primary btn-lg btn-block'><%= link_to category.name, leave_category_path(category) %></button>
<% end %>
<% if @categories.empty? %>
    <h1 class='centered'>   No Categories yet, please create them. </h1>
<% end %>
</div>

app/views/leave/categories/new.html.erb
<button class='btn btn-info btn-lg bottom-flat'>New Leave Category</button>
<div class='well'>
<% if @category.errors.any? %>
    <p class='alert alert-danger'>Errors</p>
    <% @category.errors.full_messages.each do |e| %>
        <p class='text-danger'><%= e %></p>
    <% end %>
<% end %>
<%= form_for @category, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    <br />
    <%= f.text_area :description, size: "60x12", class: 'form-control', placeholder: 'Description'   %>
    <br />
    <%= f.submit "Create", class: "btn btn-primary"%>

<% end %>
</div>

app/views/leave/categories/show.html.erb
<button class='btn btn-info btn-lg bottom-flat'>Leave Category Details</button>
<div class='well'>
    <dl class='dl-horizontal'>
        <dt>Name: </dt>
        <dd><%= @category.name %></dd>

        <dt>Description: </dt>
        <dd><%= @category.description %></dd>
    </dl>
    <% if current_user.has_role? :admin %>
    <%= link_to :Edit, edit_leave_category_path(@category), class: "btn btn-primary" %>
    <% end %>
</div>