config/routes.rb
AgencyBox::Application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :expenses
  
  namespace :expense do
    resources :categories, :only => [:new]
    get "categories/:slug" => "categories#show", as: "category"
    resources :categories, :except => [:show, :new]
  end

  namespace :leave do
    resources :categories
  end

  resources :leaves

  resources :users, only: [:index, :show]
  get "profile/edit" => "users#edit", as: "edit_user"
  patch "users/:id" => "users#update", as: "update_user"

  get "message/:id/new" => "message#new", as: :message_new
  post "message/:id/create" => "message#create", as: :message_create
  get "message/inbox" => "message#inbox", as: "message_inbox"
  get "message/sent" => "message#sent", as: "message_sent"

  get "message/:id/reply" => "message#new_reply", as: :message_reply_new
  post "message/:id/reply" => "message#send_reply", as: :message_send_reply
  get "message/:id/" => "message#show", as: :message_show

  resources :projects, :except => [:show, :edit]
  get "projects/:slug" => "projects#show", as: "project_show"
  get "projects/:slug/edit" => "projects#edit", as: "edit_project"
  patch "projects/:slug/update" => "projects#update"

  get "projects/:slug/members/add" => "project_members#new", as: "add_project_members"
  post "projects/:slug/members/add" => "project_members#create"
  
  get "tickets/" => "tickets#index"
  namespace :project do 
    get ":namespace_slug/tickets/new" => "tickets#new", as: :new_ticket
    get ":namespace_slug/tickets/" => "tickets#index", as: :tickets
    get ":namespace_slug/tickets/:id" => "tickets#show", as: :ticket
    get ":namespace_slug/tickets/:id/edit" => "tickets#edit", as: :edit_ticket
    post ":namespace_id/tickets" => "tickets#create"
    patch ":namespace_slug/tickets/:id/edit" => "tickets#update"
  end

  post "ticket/:ticket_id/ticket_comment/create" => "ticket_comment#create", as: :ticketcomment_create

  resources :leads do
      collection do
          delete :delete_multiple
      end
  end
  get "leads/dashboard"
  post "leads/convert", as: :convert_lead
 
  namespace :lead do
      resources :sources do
          collection do
              delete :delete_multiple
          end
      end
  end

  

end

app/views/shared/_project_menu.html.erb
<ul class="nav nav-pills nav-justified">
    <% if @project %>
        <% if @project.id %>
    <li id="project-subnav-li"><%= link_to @project.name, project_show_path(@project.slug) %></li>
    <li id="tickets-subnav-li"><%= link_to :Tickets, project_tickets_path(@project.slug) %></li>
    <li id="new-ticket-subnav-li"><%= link_to "New Ticket", project_new_ticket_path(@project.slug) %></li>
        <% end %>
    <% elsif @ticket %>
    <li id="project-subnav-li"><%= link_to @ticket.project.name, project_show_path(@ticket.project.slug) %></li>
    <li id="tickets-subnav-li"><%= link_to :Tickets, project_tickets_path(@ticket.project.slug) %></li>
    <li id="new-ticket-subnav-li"><%= link_to "New Ticket", project_new_ticket_path(@ticket.project.slug) %></li>
    <% end %>
</ul>
    <% if params[:controller] == "projects" and params[:action] == "index" %>
        <button class='btn btn-info btn-lg bottom-flat'>Projects</button>
    <% end %>