config/routes.rb
AgencyBox::Application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :expenses
  
  namespace :expense do
    resources :categories, :only => [:new]
    get "categories/:slug" => "categories#show", as: "category"
    resources :categories, :except => [:show, :new]
  end

  namespace :leave do
    resources :categories
  end

  resources :leaves

  resources :users, only: [:index, :show]
  get "profile/edit" => "users#edit", as: "edit_user"
  patch "users/:id" => "users#update", as: "update_user"

  get "message/:id/new" => "message#new", as: :message_new
  post "message/:id/create" => "message#create", as: :message_create
  get "message/inbox" => "message#inbox", as: "message_inbox"
  get "message/sent" => "message#sent", as: "message_sent"

  get "message/:id/reply" => "message#new_reply", as: :message_reply_new
  post "message/:id/reply" => "message#send_reply", as: :message_send_reply
  get "message/:id/" => "message#show", as: :message_show

  resources :projects, :except => [:show, :edit]
  get "projects/:slug" => "projects#show", as: "project_show"
  get "projects/:slug/edit" => "projects#edit", as: "edit_project"
  patch "projects/:slug/update" => "projects#update"

  get "projects/:slug/members/add" => "project_members#new", as: "add_project_members"
  post "projects/:slug/members/add" => "project_members#create"
  
  get "tickets/" => "tickets#index"
  namespace :project do 
    get ":namespace_slug/tickets/new" => "tickets#new", as: :new_ticket
    get ":namespace_slug/tickets/" => "tickets#index", as: :tickets
    get ":namespace_slug/tickets/:id" => "tickets#show", as: :ticket
    get ":namespace_slug/tickets/:id/edit" => "tickets#edit", as: :edit_ticket
    post ":namespace_id/tickets" => "tickets#create"
    patch ":namespace_slug/tickets/:id/edit" => "tickets#update"
  end

  post "ticket/:ticket_id/ticket_comment/create" => "ticket_comment#create", as: :ticketcomment_create

  resources :leads do
      collection do
          delete :delete_multiple
      end
  end
  get "leads/dashboard"
  post "leads/convert", as: :convert_lead
 
  namespace :lead do
      resources :sources do
          collection do
              delete :delete_multiple
          end
      end
  end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :created_by, class_name: :User, foreign_key: :created_by_id

    has_many :project_members
    has_many :members, class_name: :User, through: :project_members, uniq: true

    has_many :tickets

    #validations
    validates :name, presence: true, length: { :minimum => 5 }
    validates :description, presence: true, length: { :minimum => 5 }
    validate :create_and_validate_slug
    validates :slug, :uniqueness => { 
        message: ": Project with this name already exists, 
        please choose another name" }

    def create_and_validate_slug
        self.slug = self.name.parameterize
    end

    def add_members(users)
        for user_id in users
            if ProjectMember.find_by(member_id: user_id, project: self).nil?
                self.members.append User.find(user_id)
            end
        end
    end

    def get_members
        res = []
        self.members.each do |member|
            res << [member.available_name, member.id]
        end
        return res
    end




end

app/controllers/project/tickets_controller.rb
class Project::TicketsController < ApplicationController
    #before_filter :authenticate_user!
    #before_filter :admin_employee_auth, only: [:new, :edit, :create, :modify, :tickets]
    before_filter :authenticate_user!


    def tickets
        @tickets = Ticket.where(assigned_to: current_user)
    end

    def index
        @project = Project.find_by_slug params[:namespace_slug]
        @tickets = @project.tickets
    end

    def new
        @ticket = Ticket.new
        @project = Project.find_by_slug params[:namespace_slug]
        @project_members = @project.get_members
        if @project_members.empty?
            flash[:notice] = "Please add members to the project before using tickets"
            redirect_to add_project_members_path(slug: @project.slug)
        end
    end

    def edit
        @ticket = Ticket.find params[:id]
        @project = Project.find_by_slug params[:namespace_slug]
    end

    def create
        @ticket = Ticket.new new_ticket_params
        @ticket.status = "New"
        @ticket.reported_by = current_user
        @ticket.project_id = params[:namespace_id]
        @ticket.save
        flash[:notice] = "You have created a new ticket '#{new_ticket_params[:name]}'"
        redirect_to project_ticket_path({ :namespace_slug => @ticket.project.slug, :id => @ticket })
    end

    def update 
        @ticket = Ticket.find params[:id]
        @ticket.assign_attributes edit_ticket_params
        changed = @ticket.changed

        #Create comment when a ticket is modified
        comment = TicketComment.new
        content = "changed "
        changed.each do |changed_item|
            if changed_item == "assigned_to_id"
                assigned_to_was = User.find @ticket.assigned_to_id_was
                content += "<span class='ticket_changed_field_name'>assigned to</span> from <span class='ticket_changed_from'>#{assigned_to_was.available_name}</span> to <span class='ticket_changed_to'>#{@ticket.assigned_to.available_name}</span>, "
            else
                content += "<span class='ticket_changed_field_name'>#{changed_item}</span> from <span class='ticket_changed_from'>#{@ticket.send(changed_item+"_was")}</span> to <span class='ticket_changed_to'>#{@ticket[changed_item]}</span>, "
            end
        end
        if changed.any? 
            content = content.strip.chomp(",")
            TicketComment.create(ticket: @ticket, content: content, created_by: current_user)
        end

        @ticket.save
        redirect_to project_ticket_path({ :namespace_slug => @ticket.project.slug, :id => @ticket })
    end

    def show
        @ticket = Ticket.find params[:id]
        @ticket_comment = TicketComment.new
    end

    private

    def new_ticket_params
        params.require(:ticket).permit(:name, :description, :assigned_to_id)
    end

    def edit_ticket_params
        params.require(:ticket).permit(:name, :description, :assigned_to_id, :status)
    end

    def admin_employee_auth
        @project = Project.find params[:namespace_id]
        @project.is_member?(current_user.id) || not_found
    end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
    before_filter :authenticate_user!

    
    def new
        @project = Project.new
    end

    def create
        @project = Project.new new_project_params
        if @project.valid?
            @project.created_by = current_user
            @project.save
            redirect_to project_show_path(slug: @project.slug)
        else
            render :new
        end
    end

    def edit
        @project = Project.find_by_slug params[:slug]
    end

    def modify
        @project = Project.find_by_slug params[:slug]
        @project.assign_attributes new_project_params
        
        if @project.valid?
            @project.save
            redirect_to project_show_path(slug: @project.slug)
        else
            render :edit
        end
    end

    def show
        @project = Project.find_by slug: params[:slug]
    end

    def index
        @projects = Project.where created_by: current_user
    end

    private

    def new_project_params
        params.require(:project).permit(:name, :description)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_filter :authenticate_user!

    
    def new
        @project = Project.new
    end

    def create
        @project = Project.new new_project_params
        if @project.valid?
            @project.created_by = current_user
            @project.save
            redirect_to project_show_path(slug: @project.slug)
        else
            render :new
        end
    end

    def edit
        @project = Project.find_by_slug params[:slug]
    end

    def update
        @project = Project.find_by_slug params[:slug]
        @project.assign_attributes new_project_params
        
        if @project.valid?
            @project.save
            redirect_to project_show_path(slug: @project.slug)
        else
            render :edit
        end
    end

    def show
        @project = Project.find_by slug: params[:slug]
    end

    def index
        @projects = Project.where created_by: current_user
    end

    private

    def new_project_params
        params.require(:project).permit(:name, :description)
    end

end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/projects/edit.html.erb
<button class='btn btn-info btn-lg bottom-flat max-width'>Edit Project</button>
<div class='well'>
<% if @project.errors.any? %>
    <p class='alert alert-danger'>Errors</p>
    <% @project.errors.full_messages.each do |e| %>
        <p class='text-danger'><%= e %></p>
    <% end %>
<% end %>
<%= form_for @project, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    <br />
    <%= f.text_area :description, size: "60x12", class: 'form-control', placeholder: 'Description'   %>
    <br />
    <%= f.submit "Edit", class: "btn btn-primary"%>

<% end %>
</div>

app/views/projects/index.html.erb
<div class='well'>
<% @projects.each do |project| %>
    <button class='btn btn-primary btn-lg btn-block'><%= link_to project.name, project_show_path(project.slug) %></button>
<% end %>
<% if @projects.empty? %>
    <h1 class='centered'>No projects yet !</h1>
<% end %>
</div>

app/views/projects/new.html.erb
<button class='btn btn-info btn-lg bottom-flat max-width'>New Project</button>
<div class='well'>
<% if @project.errors.any? %>
    <p class='alert alert-danger'>Errors</p>
    <% @project.errors.full_messages.each do |e| %>
        <p class='text-danger'><%= e %></p>
    <% end %>
<% end %>
<%= form_for @project, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    <br />
    <%= f.text_area :description, size: "60x12", class: 'form-control', placeholder: 'Description'   %>
    <br />
    <%= f.submit "Create", class: "btn btn-primary"%>

<% end %>
</div>

app/views/projects/show.html.erb
<button class='btn btn-info btn-lg bottom-flat max-width'><%= @project.name %></button>
<div class='well'>
    <dl class="dl-horizontal">
        <dt>Name: </dt>
        <dd><%= @project.name %></dd>

        <dt>Description: </dt>
        <dd><%= @project.description %></dd>
    </dl>

    <% if current_user.has_role? :admin %>
        <%= link_to :Edit, edit_project_path(@project.slug), class: "btn btn-primary" %>
    <% end %>
</div>

<button class='btn btn-info btn-lg bottom-flat'>Members</button>
<div class='well'>
    <div><%= link_to "Add", add_project_members_path(@project.slug), {class: 'btn btn-primary'} %> </div>
<% @project.members.each do |member| %>

    <div>
    <%= link_to member.available_name, user_path(member) %>
    </div>

<% end %>
<% if @project.members.count.zero? %>
    No members for this project !
<% end %>
</div>