config/routes.rb
AgencyBox::Application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :expenses
  
  namespace :expense do
    resources :categories, :only => [:new]
    get "categories/:slug" => "categories#show", as: "category"
    resources :categories, :except => [:show, :new]
  end

  namespace :leave do
    resources :categories
  end

  resources :leaves

  resources :users, only: [:index, :show]
  get "profile/edit" => "users#edit", as: "edit_user"
  patch "users/:id" => "users#update", as: "update_user"

  get "message/:id/new" => "message#new", as: :message_new
  post "message/:id/create" => "message#create", as: :message_create
  get "message/inbox" => "message#inbox", as: "message_inbox"
  get "message/sent" => "message#sent", as: "message_sent"

  get "message/:id/reply" => "message#new_reply", as: :message_reply_new
  post "message/:id/reply" => "message#send_reply", as: :message_send_reply
  get "message/:id/" => "message#show", as: :message_show

  resources :projects, :except => [:show, :edit]
  get "projects/:slug" => "projects#show", as: "project_show"
  get "projects/:slug/edit" => "projects#edit", as: "edit_project"
  patch "projects/:slug/update" => "projects#update"

  get "projects/:slug/members/add" => "project_members#new", as: "add_project_members"
  post "projects/:slug/members/add" => "project_members#create"
  
  get "tickets/" => "tickets#index"
  namespace :project do 
    get ":namespace_slug/tickets/new" => "tickets#new", as: :new_ticket
    get ":namespace_slug/tickets/" => "tickets#index", as: :tickets
    get ":namespace_slug/tickets/:id" => "tickets#show", as: :ticket
    get ":namespace_slug/tickets/:id/edit" => "tickets#edit", as: :edit_ticket
    post ":namespace_id/tickets" => "tickets#create"
    patch ":namespace_slug/tickets/:id/edit" => "tickets#update"
  end

  post "ticket/:ticket_id/ticket_comment/create" => "ticket_comment#create", as: :ticketcomment_create

  resources :leads do
      collection do
          delete :delete_multiple
      end
  end
  get "leads/dashboard"
  post "leads/convert", as: :convert_lead
 
  namespace :lead do
      resources :sources do
          collection do
              delete :delete_multiple
          end
      end
  end

  

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
    #before_filter :authenticate_user!, :add_to_crumbs
    before_filter :authenticate_user!



    def index
        if current_user.has_role? :admin
            @expenses = Expense.all
        else
            @expenses = Expense.where user: current_user
        end
        if params.include?("status")
            if params['status'] == "pending"
                @expenses = @expenses.where({ :status => false, :rejected => false })
            elsif params["status"] == "approved"
                @expenses = @expenses.where({ :status => true, :rejected => false })
            elsif params["status"] == "rejected"
                @expenses = @expenses.where({ :status => false, :rejected => true })
            end
        end

        if params.include?(:amount_filter)
            if params[:amount_filter] == "asc"
                @expenses = @expenses.order("amount ASC")
            elsif params[:amount_filter] == "desc"
                @expenses = @expenses.order("amount desc")
            end
        end

        if params.include?(:user)
            if current_user.has_role? :admin
                @expenses = @expenses.where(:user_id => params[:user])
            end
        end

        @users = User.all
    end

    def new
        @expense = Expense.new
    end

    def create
        @expense = Expense.new create_expense_params
        if @expense.valid?
            @expense.user = current_user
            @expense.save
            UserMailer.new_expense(@expense).deliver
            redirect_to :expenses
        else
            render :new
        end
    end

    def show
        @expense = Expense.find params[:id]
    end

    def edit
        @expense = Expense.find params[:id]
    end

    def update
        expense = Expense.find params[:id]
        expense_status = params[:expense_status]
        if expense_status == "Approved"
            expense.status = true
            expense.rejected = false
        elsif expense_status == "Pending"
            expense.status = false
            expense.rejected = false
        elsif expense_status == "Rejected"
            expense.status = false
            expense.rejected = true
        end
        expense.save
        redirect_to expense_path(expense)
    end

    private

    #def add_to_crumbs
    #    '''
    #    Not used now, but can be used when exact crumbs are required.
    #    Currently using simply crumbs using javascript
    #    '''
    #    @crumbs.append ["Expenses", expense_index_path() ]
    #end

    def create_expense_params
        params.require(:expense).permit(:amount, :category_id, :description)
    end

end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/edit.html.erb
<button class='btn btn-info btn-lg bottom-flat'>Expense Edit</button>
<div class='well expense-edit'>
    <dl class='dl-horizontal'>
        <dt>Amount:</dt>
        <dd><%= @expense.amount %></dd>

        <dt>User:</dt>
        <dd><%= link_to @expense.user.available_name, user_path(@expense.user) %></dd>

        <dt>Status:</dt>
        <dd><%= @expense.status_display %></dd>

        <dt>Modify Status:</dl>
        <dd></dd>
    </dl>
    
        <div class="edit-form-div">
            <form action='<%= url_for({ controller: :expenses, action: :update, id: @expense.id}) %>' method='post'>
            <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>' />
            <input name="_method" type="hidden" value="patch" />
                <select name='expense_status' class="form-control">
                    <option value='Pending'>Pending</option>
                    <option value='Approved'>Approve</option>
                    <option value='Rejected'>Reject</option>
                </select>
                <input type='submit' class='btn  btn-primary' value='Edit' />
            </form>
        </div>

</div>

app/views/expenses/index.html.erb
<div class="left-pane">
<button class='btn btn-info btn-lg bottom-flat' id="filter-main-btn">Filter</button>
<div class="well filter-box" >

    <div id="amount-filter-box" class="small-box">
        <div class="box-header">
            Amount
        </div>
        <div class="box-content">
            <p>
            <input type="radio" name="amount" id="filter_by_asc" value="asc" /> Asc
            </p>
            <p>
            <input type="radio" name="amount" id="filter_by_desc" value="desc" /> Desc
            </p>
            <p>
            <input type="radio" name="amount" value="none" /> Reset
            </p>
        </div>
    </div>
    <div id="status-filter-box" class="small-box">
        <div class="box-header">
            Status 
        </div>
        <div class="box-content">
            <p>
            <input type="radio" name="status" id="filter_by_status_pending" value="pending" /> Pending
            </p>
            <p>
            <input type="radio" name="status" id="filter_by_status_rejected" value="rejected" /> Rejected
            </p>
            <p>
            <input type="radio" name="status" id="filter_by_status_approved" value="approved" /> Approved
            </p>
            <p>
            <input type="radio" name="status" id="filter_by_status_none" value="none" /> Reset
            </p>

        </div>
    </div>
    <% if current_user.has_role? :admin %>
    <div id="user-filter-box" class="small-box">
        <div class="box-header">
            User
        </div>
        <div class="box-content">
            <p>
                <select id="users_list">
                    <option value>-------</option>
                    <% @users.each do |user| %>
                        <option value="<%= user.id %>"><%= user.available_name %></option>
                    <% end %>
                </select>
            </p>
        </div>
    </div>
    <% end %>


    <button id="submit-filter" class="btn btn-primary">Filter</button>
    <button id="reset-btn" class="btn btn-primary">Reset</button>
</div>
</div>
<div class='right-pane'>
<button class='btn btn-info btn-lg bottom-flat'>Expenses</button>
    <div class='well' id="expenses">
<% @expenses.each do |expense| %>
    <div class='expense'>
        <% if current_user.has_role? :admin %>
        <span class='medium-text'><%= link_to "#{expense.amount} by #{expense.user.available_name}", edit_expense_path(expense) %></span>
        <% else %>
        <span class='medium-text'><%= link_to "#{expense.amount}", expense_path(expense) %></span>
        <% end %>
        
        <% if expense.status_display == "Pending" %>
        <div class="badge badge-warning">Pending</div>
        <% elsif expense.status_display == "Rejected" %>
            <div class="badge badge-error">Rejected</div>
        <% elsif expense.status_display == "Approved" %>
            <div class="badge badge-success">Approved</div>
        <% end %>
    </div>
<% end %>
<% if @expenses.length.zero? %>
No expenses found for this filter !
<% end %>
</div>

app/views/expenses/new.html.erb
<button class='btn btn-info btn-lg bottom-flat'>New Expense</button>
<div class='well'>
<% if @expense.errors.any? %>
    <p class='alert alert-danger'>Errors</p>
    <% @expense.errors.full_messages.each do |e| %>
        <p class='text-danger'><%= e %></p>
    <% end %>
<% end %>
<%= form_for @expense, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <%= f.text_field :amount , class: 'form-control', placeholder: 'Amount' %>
    <br />
    <%= f.text_area :description, size: "60x12", class: 'form-control', placeholder: 'Description'   %>
    <br />
    <%= f.select :category_id, Categories: @expense.categories %>
    <%= f.submit "Create", class: "btn btn-primary"%>

<% end %>
</div>

app/views/expenses/show.html.erb
<button class='btn btn-info btn-lg bottom-flat'>Expense Details</button>
<div class='well'>
    <dl class='dl-horizontal'>
        <dt>Amount: </dt>
        <dd><%= @expense.amount %></dd>

        <dt>Description: </dt>
        <dd><%= @expense.description %></dd>

        <dt>Status:</dt>
        <dd><%= @expense.status_display %></dd>

        <dt>Category: </dt>
        <dd><%= link_to @expense.category.name, expense_category_path(@expense.category.slug) %></dd>
    </dl>
    <% if current_user.has_role? :admin %>
    <%= link_to :Edit, :edit_expense %>
    <% end %>
</div>